modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
	modId="concreteconversiontech"
	version="${version}"
	displayName="Concrete Conversion Tech"
	logoFile="ConcreteConversionTechLogo.png"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConcreteConversionTech.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/concrete-conversion-tech/issues"
	displayURL="https://minecraft.curseforge.com/projects/concrete-conversion-tech"
	authors="mrp_v2"
	description='''Adds simple machines for automating conversion of concrete powder into concrete.'''
[[dependencies.concreteconversiontech]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.concreteconversiontech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"