modLoader="javafml"
loaderVersion="[${majorForgeVersion},)"
license="All rights reserved"
[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="Concrete Conversion Tech"
	logoFile="ConcreteConversionTechLogo.png"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConcreteConversionTech.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/concrete-conversion-tech/issues"
	displayURL="https://minecraft.curseforge.com/projects/concrete-conversion-tech"
	authors="mrp_v2"
	description='''Adds simple machines for automating conversion of concrete powder into concrete.'''
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[${majorForgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="configurablerecipeslibrary"
    mandatory=true
    versionRange="[${mcVersion}-1.0,)"
    ordering="NONE"
    side="BOTH"